from typing import TypedDict, Annotated, Sequence
from langchain_core.messages import BaseMessage
from langchain_core.documents import Document
from langgraph.graph.message import add_messages

class GraphState(TypedDict):
    """
    Represents the state of the RAG pipeline.
    
    Note: Dynamic execution settings (e.g., relevance_threshold) are managed 
    via LangGraph's native `RunnableConfig` rather than this state dictionary.
    """

    # Chat history (automatically appended to, not overwritten)
    messages: Annotated[Sequence[BaseMessage], add_messages]
    
    # The original query provided by the user
    raw_query: str
    
    # The LLM-reformulated query optimized for vector search
    search_query: str
    
    # The filtered, high-relevance document chunks retrieved from the index
    documents: Sequence[Document]
    
    # The final response generated by the LLM
    generation: str

    # The classified intent of the query (e.g., "qa", "summary", "chitchat")
    # Determines the routing path in the graph execution
    intent: str
    
    # The resolved source filename targeted for summarization requests
    # Retained in state primarily for evaluation and debugging purposes
    target_source: str